# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - siapkan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_b0f5c3de84184efaa714187680d05a27 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a47e8868c0c041b4a55a9413e90aff26 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_b0f5c3de84184efaa714187680d05a27 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'siapkan'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4de5f39dcb3748118611fd7b7713fdf0 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_b0f5c3de84184efaa714187680d05a27 }}/appsvc/staticsite:${{ github.sha }}'